name: Rust CI/CD

# run workflow when the condition is met
on:
  # run when code is pushed on the `main` branch
  push:
    branches: ['main']
  # run when a pull request to the `main` branch
  pull_request:
    branches: ['main']

# env variables
env:
  CARGO_TERM_COLOR: always

# jobs
jobs:
  # job name
  build:
    # os to run the job on support macOS and windows also
    runs-on: ubuntu-latest
    # steps for job
    steps:
      # this will get the code and set the git
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt

      - name: Check formatting
        run: cargo fmt -- --check

      - name: Lint with Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      # run the build
      - name: Build
        # using cargo to build
        run: cargo build --release

      # run the tests
      - name: Test
        # using cargo to test
        run: cargo test

      # for deployment
      - name: make dir
        # create a directory
        run: mkdir app
      # put the app in it
      - name: copy
        run: mv ./target/release/timestamp-microservice ./app/axum

      # heroku deployment
      - uses: akhileshns/heroku-deploy@v3.12.14
        with:
          # key from repository secrets
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          # name of the Heroku app
          heroku_app_name: 'timestamp-microservice-ll'
          # email from which the app is uploaded
          heroku_email: ${{secrets.HEROKU_EMAIL}}

          # app directory
          appdir: './app'

          # start command
          procfile: 'web: ./axum'
          # buildpack is like environment used to run the app
          buildpack: 'https://github.com/ph3nx/heroku-binary-buildpack.git'
